const order=["core","coils","aperture","bus","housing","thermal","interface"];
const state={gen:"mark1",component:"core",subpart:null,coilIndex:null,level:1,explode:0,xray:false,isolate:false,identify:true,zoom:1,view:"front"};
const $=id=>document.getElementById(id);let THREE,scene,camera,renderer,root,ray,pointer;let rx=0,ry=0,drag=false,moved=false,lx=0,ly=0;const groups={},meshes=[],anchors={};let flyTarget=null;
function bc(t){return t==="canon"?"canon":t==="visual"?"visual":"infer"}function active(){return C[state.component]}
function renderTree(){$("tree").innerHTML="";order.forEach(k=>{const c=C[k],b=document.createElement("button");b.className="treeBtn"+(state.component===k?" active":"");b.innerHTML=`<strong>${c.name}</strong><span>${c.badge}</span>`;b.onclick=()=>selectComponent(k);$("tree").appendChild(b)})}
function renderSubs(){const c=active(),s=c.subs||[];$("subcount").textContent=String(s.length).padStart(2,"0");$("subgrid").innerHTML="";s.forEach(([id,n,t])=>{const b=document.createElement("button");b.className="partBtn"+(state.subpart===id?" active":"");b.innerHTML=`<strong>${n}</strong><span>${t}</span>`;b.onclick=()=>selectSubpart(id,n);$("subgrid").appendChild(b)})}
function selectComponent(k){state.component=k;state.subpart=null;state.coilIndex=null;const c=C[k];$("partName").textContent=c.name;$("badge").textContent=c.badge;$("badge").className="badge "+bc(c.type);$("definition").textContent=c.definition;$("makeup").textContent=c.makeup;$("role").textContent=c.role;$("canonText").textContent=c.canon;$("crumbText").textContent=state.level>1?c.name.toUpperCase():"ASSEMBLY";renderTree();renderSubs();applyVisibility();updateCallouts()}
function selectSubpart(id,name){state.level=3;state.subpart=id;$("crumbText").textContent=name.toUpperCase();$("hudLevel").textContent="PHYSICAL PART";applyVisibility();updateCallouts();focusSelection()}
function setGen(g){state.gen=g;state.component="core";state.subpart=null;state.coilIndex=null;state.level=1;state.explode=0;$("explode").value=0;const d=GEN[g];document.querySelectorAll("[data-gen]").forEach(b=>b.classList.toggle("active",b.dataset.gen===g));$("modelTitle").textContent=d.title;$("modelCode").textContent=d.code;$("hudModel").textContent=d.code;$("sysText").textContent=d.status;$("mCore").textContent=d.core;$("mCoils").textContent=d.coils;$("mParts").textContent=d.parts;$("note").textContent=d.note;$("crumbText").textContent="ASSEMBLY";build();selectComponent("core");frontView()}
function log(t){$("cmdlog").textContent="JARVIS> "+t}
function mat(color,metal=.65,rough=.28,op=1,em=0x000000,ei=.12){const m=new THREE.MeshStandardMaterial({color,metalness:metal,roughness:rough,transparent:op<1,opacity:op,emissive:em,emissiveIntensity:ei,side:THREE.DoubleSide});m.userData.baseOpacity=op;return m}
function glow(c=0x6ce8ff,op=.45){const m=new THREE.MeshPhysicalMaterial({color:c,emissive:c,emissiveIntensity:1.15,metalness:.05,roughness:.14,transparent:true,opacity:op,transmission:.1,thickness:.18,side:THREE.DoubleSide});m.userData.baseOpacity=op;return m}
function cg(k){const g=new THREE.Group();g.userData.component=k;groups[k]=g;root.add(g);return g}
function tag(o,c,s,l,extra={}){o.userData.component=c;o.userData.subpart=s||null;o.userData.label=l||C[c].name;Object.assign(o.userData,extra);meshes.push(o);return o}
function addMesh(geo,ma,c,s,l,parent=null,extra={}){const x=new THREE.Mesh(geo,ma);tag(x,c,s,l,extra);(parent||groups[c]).add(x);return x}
function cyl(r,d,z,ma,c,s,l,seg=96,parent=null,extra={}){const x=addMesh(new THREE.CylinderGeometry(r,r,d,seg),ma,c,s,l,parent,extra);x.rotation.x=Math.PI/2;x.position.z=z;return x}
function tor(r,t,z,ma,c,s,l,parent=null,extra={}){const x=addMesh(new THREE.TorusGeometry(r,t,14,96),ma,c,s,l,parent,extra);x.position.z=z;return x}
function box(w,h,d,x,y,z,rz,ma,c,s,l,parent=null,extra={}){const q=addMesh(new THREE.BoxGeometry(w,h,d),ma,c,s,l,parent,extra);q.position.set(x,y,z);q.rotation.z=rz;return q}
function rbox(r,a,w,h,d,z,ma,c,s,l,parent=null,extra={}){return box(w,h,d,Math.sin(a)*r,Math.cos(a)*r,z,-a,ma,c,s,l,parent,extra)}
function clear(){if(root)scene.remove(root);root=new THREE.Group();scene.add(root);meshes.length=0;Object.keys(groups).forEach(k=>delete groups[k]);Object.keys(anchors).forEach(k=>delete anchors[k]);order.forEach(cg)}
function rectangleLoop(w,h,radius,z){const pts=[];const n=5;for(let i=0;i<n;i++)pts.push(new THREE.Vector3(-w/2+i*w/(n-1),h/2,z));for(let i=1;i<n;i++)pts.push(new THREE.Vector3(w/2,h/2-i*h/(n-1),z));for(let i=1;i<n;i++)pts.push(new THREE.Vector3(w/2-i*w/(n-1),-h/2,z));for(let i=1;i<n-1;i++)pts.push(new THREE.Vector3(-w/2,-h/2+i*h/(n-1),z));const curve=new THREE.CatmullRomCurve3(pts,true,"catmullrom",.06);return new THREE.TubeGeometry(curve,48,radius,6,true)}
function coilPack(i,count,r,z,clean=false){const a=i/count*Math.PI*2,g=new THREE.Group();g.position.set(Math.sin(a)*r,Math.cos(a)*r,z);g.rotation.z=-a;groups.coils.add(g);const core=addMesh(new THREE.BoxGeometry(.43,.37,.17),mat(0x202a2f,.38,.5),"coils","coil_core",`Coil ${String(i+1).padStart(2,"0")} core`,g,{coilIndex:i+1});for(let n=0;n<10;n++){const loop=addMesh(rectangleLoop(.50+n*.003,.45+n*.002,.0105,(n-4.5)*.016),mat(clean?0xd08b56:0xc17545,.78,.22),"coils","coil_wire",`Coil ${String(i+1).padStart(2,"0")} copper winding ${n+1}`,g,{coilIndex:i+1});loop.rotation.x=.04}[-.29,.29].forEach((ox,j)=>{const cl=addMesh(new THREE.BoxGeometry(.055,.54,.22),mat(clean?0xb9c5c9:0x85949a,.86,.2),"coils","coil_clamp",`Coil ${String(i+1).padStart(2,"0")} clamp ${j+1}`,g,{coilIndex:i+1});cl.position.x=ox});const term=addMesh(new THREE.BoxGeometry(.13,.13,.09),mat(0xad7446,.8,.22),"coils","coil_terminal",`Coil ${String(i+1).padStart(2,"0")} terminal`,g,{coilIndex:i+1});term.position.set(0,-.31,-.02);if(i===0)anchors.coils=g}
function addMeshFace(z){const g=new THREE.Group();groups.core.add(g);const ma=mat(0xb8c4c8,.8,.26);for(let i=-4;i<=4;i++){const a=box(.018,.62,.025,i*.065,0,z,0,ma,"core","center_mesh","Center mesh vertical",g);const b=box(.62,.018,.025,0,i*.065,z,0,ma,"core","center_mesh","Center mesh horizontal",g)}return g}
function buildCircular(clean=false){const steel=mat(clean?0xc5cfd2:0x8e9ba0,.88,clean?.16:.28),dark=mat(0x252e32,.72,.34),black=mat(0x10171a,.45,.5),copper=mat(0xb77848,.75,.24),brass=mat(0xb9a068,.82,.2),acrylic=glow(0xbef7ff,.22);
 cyl(2.72,.15,-.69,dark,"housing","rear_plate","Rear housing plate");cyl(2.53,.07,-.59,steel,"housing","rear_plate","Rear face");
 tor(2.56,.105,-.31,steel,"housing","outer_ring","Outer capture ring");tor(2.28,.05,-.20,steel,"housing","outer_ring","Inner capture ring");
 cyl(2.34,.15,-.18,acrylic,"housing","light_body","Translucent illuminated body");
 for(let i=0;i<12;i++){const a=i/12*Math.PI*2;rbox(2.60,a,.16,.18,.11,-.18,steel,"housing","fastener",`Perimeter fastener ${i+1}`);rbox(2.39,a,.13,.26,.12,-.17,black,"housing","mount_clip",`Mount clip ${i+1}`)}
 for(let i=0;i<24;i++)rbox(2.45,i/24*Math.PI*2,.08,.30,.13,-.61,dark,"thermal","heat_fin",`Cooling fin ${i+1}`);
 cyl(2.27,.05,-.64,mat(0x47565b,.82,.28),"thermal","heat_spreader","Rear heat spreader");
 for(let i=0;i<10;i++)coilPack(i,10,1.98,.00,clean);
 tor(1.64,.04,.055,copper,"bus","bus_ring","Circular power bus");for(let i=0;i<10;i++)rbox(1.53,i/10*Math.PI*2,.045,.56,.045,.06,copper,"bus","bus_link",`Radial bus link ${i+1}`);
 cyl(1.49,.075,.10,black,"aperture","slot_ring","Dark slotted aperture ring");
 for(let i=0;i<28;i++){const a=i/28*Math.PI*2;rbox(1.34,a,.08,.25,.08,.16,glow(0xd6fbff,.52),"aperture","slot_window",`Aperture window ${i+1}`);rbox(1.34,a,.045,.30,.04,.095,steel,"aperture","slot_ring",`Aperture divider ${i+1}`)}
 tor(1.12,.055,.20,brass,"aperture","inner_ring","Outer brass inner ring");tor(.95,.035,.235,steel,"aperture","inner_ring","Steel inner ring");tor(.81,.035,.26,brass,"core","brass_ring","Core contact ring");
 for(let i=0;i<3;i++){const a=i/3*Math.PI*2;rbox(.97,a,.11,.87,.065,.31,steel,"aperture","front_spoke",`Front retaining spoke ${i+1}`)}
 tor(.69,.055,.30,steel,"core","core_collar","Core retaining collar");cyl(.60,.055,.33,glow(0xcaf9ff,.42),"core","core_diffuser","Core light diffuser");addMeshFace(.38);
 cyl(.30,.14,.31,mat(0xcbd4d7,.9,.16),"core","core_cartridge","Palladium core cartridge",64);tor(.32,.035,.405,brass,"core","brass_ring","Front core ring");
 const conn=box(.64,.36,.22,-1.73,-2.18,-.48,0,mat(0x63747b,.8,.25),"interface","load_connector","Chest / load connector");box(.11,.22,.10,-1.89,-1.98,-.35,0,copper,"interface","load_contact","Load contact A");box(.11,.22,.10,-1.57,-1.98,-.35,0,copper,"interface","load_contact","Load contact B");
 anchors.core=groups.core;anchors.aperture=groups.aperture;anchors.housing=groups.housing;anchors.thermal=groups.thermal;anchors.bus=groups.bus;anchors.interface=conn
}
function bar(p1,p2,w,d,z,ma,c,s,l){const dx=p2.x-p1.x,dy=p2.y-p1.y,len=Math.hypot(dx,dy),ang=Math.atan2(dx,dy);return box(w,len,d,(p1.x+p2.x)/2,(p1.y+p2.y)/2,z,-ang,ma,c,s,l)}
function buildMark6(){const steel=mat(0xc5ced1,.9,.16),dark=mat(0x273238,.75,.29),copper=mat(0xb77a49,.76,.22),cyan=glow(0x6ce8ff,.48);
 cyl(2.68,.15,-.62,dark,"housing","rear_plate","Rear housing");tor(2.49,.115,-.28,steel,"housing","outer_ring","Outer capture ring");cyl(2.26,.12,-.12,cyan,"housing","light_body","Illuminated body");
 for(let i=0;i<30;i++)rbox(2.27,i/30*Math.PI*2,.09,.28,.12,-.10,steel,"coils","coil_core",`Outer stator segment ${i+1}`);
 for(let i=0;i<12;i++)rbox(2.50,i/12*Math.PI*2,.13,.16,.10,-.10,steel,"housing","fastener",`Fastener ${i+1}`);
 const p=[{x:0,y:1.28},{x:1.11,y:-.66},{x:-1.11,y:-.66}],q=[{x:0,y:.58},{x:.51,y:-.30},{x:-.51,y:-.30}];
 for(let i=0;i<3;i++){bar(p[i],p[(i+1)%3],.14,.13,.26,steel,"aperture","front_spoke","Triangular frame");bar(q[i],q[(i+1)%3],.12,.17,.38,glow(0xd5fcff,.76),"core","core_cartridge","New-element core frame");const a=i/3*Math.PI*2;rbox(1.64,a,.20,.82,.085,.08,glow(0x83efff,.30),"coils","coil_wire",`Field sector ${i+1}`);rbox(1.48,a,.07,.95,.05,.15,copper,"bus","bus_link",`Power link ${i+1}`)}
 tor(1.85,.045,.11,copper,"bus","bus_ring","Outer power bus");tor(1.25,.055,.18,steel,"aperture","inner_ring","Mark VI inner ring");cyl(.38,.17,.45,glow(0xe9ffff,.90),"core","core_diffuser","New-element aperture");
 for(let i=0;i<24;i++)rbox(2.43,i/24*Math.PI*2,.08,.27,.13,-.55,dark,"thermal","heat_fin",`Cooling fin ${i+1}`);cyl(2.25,.055,-.59,mat(0x4b595e,.82,.28),"thermal","heat_spreader","Rear heat spreader");
 const conn=box(.62,.32,.20,-1.75,-2.13,-.42,0,mat(0x697a81,.82,.23),"interface","load_connector","Armor / chest connector");
 anchors.core=groups.core;anchors.coils=groups.coils;anchors.aperture=groups.aperture;anchors.bus=groups.bus;anchors.housing=groups.housing;anchors.thermal=groups.thermal;anchors.interface=conn
}
function build(){if(!THREE)return;clear();GEN[state.gen].tri?buildMark6():buildCircular(state.gen==="refined");applyExplode();applyVisibility();updateCallouts()}