function applyExplode(){if(!root)return;const p=state.explode/100,z={core:1.65*p,aperture:1.10*p,bus:.63*p,coils:.27*p,housing:-.53*p,thermal:-1.28*p,interface:-.92*p};order.forEach(k=>groups[k].position.z=z[k]||0);$("explodeText").textContent=state.explode+"%";$("hudDepth").textContent=(p*1.65).toFixed(2);$("hudLevel").textContent=state.level===1?(p?"EXPLODED ASSEMBLY":"ASSEMBLY"):state.level===2?"SUBSYSTEM":"PHYSICAL PART"}
function applyVisibility(){if(!root)return;meshes.forEach(x=>{const k=x.userData.component;let v=true;if(state.level>=2&&k!==state.component)v=false;if(state.subpart&&k===state.component&&x.userData.subpart!==state.subpart)v=false;if(state.coilIndex&&k==="coils"&&x.userData.coilIndex!==state.coilIndex)v=false;x.visible=v;if(!v)return;const base=x.material.userData.baseOpacity??1;let op=state.xray?(k===state.component?.58:.13):base;if(state.isolate&&k!==state.component)op=.025;x.material.transparent=op<1||x.material.transparent;x.material.opacity=op;if("emissiveIntensity" in x.material)x.material.emissiveIntensity=k===state.component?.70:.12});$("xray").classList.toggle("active",state.xray);$("isolate").classList.toggle("active",state.isolate)}
function drill(){state.level=2;state.subpart=null;$("crumbText").textContent=active().name.toUpperCase();applyVisibility();updateCallouts();focusSelection()}
function exitRoot(){state.level=1;state.subpart=null;state.coilIndex=null;$("crumbText").textContent="ASSEMBLY";applyVisibility();renderSubs();updateCallouts();frontView()}
function focusSelection(){state.zoom=state.level===3?1.75:1.42;flyTarget={rx:0,ry:0,zoom:state.zoom}}
function frontView(){state.view="front";$("hudView").textContent="FRONT INSPECTION";flyTarget={rx:0,ry:0,zoom:state.level===1?1:state.level===2?1.42:1.75}}
function sectionView(){state.view="section";$("hudView").textContent="SIDE SECTION";flyTarget={rx:-.10,ry:1.15,zoom:1.12};state.explode=Math.max(state.explode,52);$("explode").value=state.explode;applyExplode()}
function resetAll(){state.level=1;state.subpart=null;state.coilIndex=null;state.explode=0;state.xray=false;state.isolate=false;state.identify=true;state.zoom=1;$("explode").value=0;$("identify").classList.add("active");applyExplode();applyVisibility();selectComponent("core");frontView()}
function init3D(T){THREE=T;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(33,1,.1,100);camera.position.z=9.5;renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0x000000,0);$("scene").appendChild(renderer.domElement);ray=new THREE.Raycaster();pointer=new THREE.Vector2();scene.add(new THREE.AmbientLight(0xc8efff,1.55));const key=new THREE.PointLight(0xffffff,9,22);key.position.set(3.5,4.2,6);scene.add(key);const fill=new THREE.PointLight(0x25c8ea,11,18);fill.position.set(-4,-2,4);scene.add(fill);const rim=new THREE.PointLight(0x78cfff,7,18);rim.position.set(2,-4,-1);scene.add(rim);const grid=new THREE.GridHelper(14,28,0x1d566a,0x102932);grid.rotation.x=Math.PI/2;grid.position.z=-1.7;grid.material.transparent=true;grid.material.opacity=.20;scene.add(grid);root=new THREE.Group();scene.add(root);build();resize();animate()}
function resize(){if(!renderer)return;const r=$("scene").getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
function animate(){requestAnimationFrame(animate);if(root){if(flyTarget){rx+=(flyTarget.rx-rx)*.10;ry+=(flyTarget.ry-ry)*.10;state.zoom+=(flyTarget.zoom-state.zoom)*.10;if(Math.abs(flyTarget.rx-rx)<.004&&Math.abs(flyTarget.ry-ry)<.004&&Math.abs(flyTarget.zoom-state.zoom)<.004)flyTarget=null}root.rotation.x+=(rx-root.rotation.x)*.12;root.rotation.y+=(ry-root.rotation.y)*.12;const s=state.zoom;root.scale.lerp(new THREE.Vector3(s,s,s),.09)}updateCalloutPositions();renderer.render(scene,camera)}
function pick(e,click=false,dbl=false){if(!renderer)return;const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(meshes.filter(x=>x.visible),false)[0],h=$("hover");if(hit){const o=hit.object;h.style.display="block";h.textContent=o.userData.label;h.style.left=(e.clientX-r.left+12)+"px";h.style.top=(e.clientY-r.top+12)+"px";renderer.domElement.style.cursor=drag?"grabbing":"pointer";if(click){selectComponent(o.userData.component);if(o.userData.component==="coils"&&o.userData.coilIndex)state.coilIndex=o.userData.coilIndex;if(state.level>=2&&o.userData.subpart){state.subpart=o.userData.subpart;state.level=3;renderSubs();applyVisibility();$("crumbText").textContent=o.userData.label.toUpperCase();focusSelection()}if(dbl&&state.level===1)drill()}}else{h.style.display="none";renderer.domElement.style.cursor=drag?"grabbing":"grab"}}
const calloutDefs={core:["CORE ASSEMBLY","Palladium / new-element center"],coils:["COIL PACKS","Individually wound copper loops"],aperture:["SLOTTED APERTURE","Windows + three front spokes"],housing:["OUTER HOUSING","Capture ring + illuminated body"],thermal:["REAR THERMAL STAGE","Inferred spreader + fins"],bus:["POWER BUS","Inferred internal conductors"],interface:["LOAD INTERFACE","Chest / armor connection"]};
function rebuildCallouts(){const wrap=$("callouts");wrap.innerHTML="";if(!state.identify)return;const keys=state.level===1?["coils","aperture","core","housing","thermal","interface"]:[state.component];keys.forEach((k,i)=>{const div=document.createElement("div");div.className="callout";div.dataset.key=k;div.innerHTML=`${calloutDefs[k][0]}<small>${calloutDefs[k][1]}</small>`;const line=document.createElement("div");line.className="leader";line.dataset.line=k;const dot=document.createElement("div");dot.className="dot";dot.dataset.dot=k;wrap.append(div,line,dot)})}
function updateCallouts(){rebuildCallouts()}
function anchorWorld(k){const obj=anchors[k]||groups[k];if(!obj||!THREE)return null;const box3=new THREE.Box3().setFromObject(obj);const c=new THREE.Vector3();box3.getCenter(c);return c}
function updateCalloutPositions(){if(!renderer||!state.identify)return;const r=renderer.domElement.getBoundingClientRect(),wrap=$("callouts");const els=[...wrap.querySelectorAll(".callout")];els.forEach((el,i)=>{const k=el.dataset.key,p=anchorWorld(k);if(!p)return;p.project(camera);const x=(p.x*.5+.5)*r.width,y=(-p.y*.5+.5)*r.height;const leftSide=i%2===0;const lx=leftSide?16:r.width-176;const ly=110+i*70;el.style.left=lx+"px";el.style.top=ly+"px";const dot=wrap.querySelector(`[data-dot="${k}"]`),line=wrap.querySelector(`[data-line="${k}"]`);dot.style.left=x+"px";dot.style.top=y+"px";const sx=leftSide?lx+145:lx,sy=ly+15,dx=x-sx,dy=y-sy,len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;line.style.left=sx+"px";line.style.top=sy+"px";line.style.width=len+"px";line.style.transform=`rotate(${ang}deg)`})}
$("viewer").onpointerdown=e=>{if(e.target.closest("button")||e.target.closest(".range")||e.target.closest(".crumb"))return;drag=true;moved=false;lx=e.clientX;ly=e.clientY;flyTarget=null};window.onpointermove=e=>{if(drag){const dx=e.clientX-lx,dy=e.clientY-ly;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;ry+=dx*.006;rx=Math.max(-.82,Math.min(.82,rx+dy*.005));lx=e.clientX;ly=e.clientY}if(renderer&&e.target===renderer.domElement)pick(e)};window.onpointerup=()=>drag=false;$("scene").onclick=e=>{if(!moved)pick(e,true,false)};$("scene").ondblclick=e=>{pick(e,true,true)};$("scene").addEventListener("wheel",e=>{e.preventDefault();flyTarget=null;state.zoom=Math.max(.60,Math.min(2.1,state.zoom+(e.deltaY>0?-.07:.07)))},{passive:false});
document.querySelectorAll("[data-gen]").forEach(b=>b.onclick=()=>setGen(b.dataset.gen));$("explode").oninput=e=>{state.explode=+e.target.value;applyExplode()};$("identify").onclick=()=>{state.identify=!state.identify;$("identify").classList.toggle("active",state.identify);updateCallouts()};$("front").onclick=frontView;$("section").onclick=sectionView;$("xray").onclick=()=>{state.xray=!state.xray;applyVisibility()};$("isolate").onclick=()=>{state.isolate=!state.isolate;applyVisibility()};$("reset").onclick=resetAll;$("drill").onclick=drill;$("center").onclick=focusSelection;$("crumb").onclick=e=>{if(e.target.dataset.root)exitRoot()};window.onresize=resize;
function command(){const s=$("cmd").value.trim().toLowerCase();if(!s)return;const map={core:"core",coil:"coils",coils:"coils",aperture:"aperture",slot:"aperture",bus:"bus",housing:"housing",thermal:"thermal",heat:"thermal",interface:"interface",connector:"interface"};let t=null;for(const k in map)if(s.includes(k))t=map[k];const ci=s.match(/coil\s*(\d+)/);if(s.includes("reset")){resetAll();log("Teardown reset.")}else if(s.includes("mark vi")||s.includes("mark 6")){setGen("mark6");log("Mark VI reactor loaded.")}else if(s.includes("refined")){setGen("refined");log("Refined palladium reactor loaded.")}else if(s.includes("mark i")||s.includes("cave")){setGen("mark1");log("Mark I cave reactor loaded.")}else if(s.includes("front")){frontView();log("Front inspection view.")}else if(s.includes("section")||s.includes("side")){sectionView();log("Side-section view.")}else if(s.includes("explode")){const n=s.match(/\d+/);state.explode=Math.max(0,Math.min(100,n?+n[0]:75));$("explode").value=state.explode;applyExplode();log(`Exploded teardown ${state.explode}%.`)}else if(ci){selectComponent("coils");state.coilIndex=Math.min(10,Math.max(1,+ci[1]));state.level=2;$("crumbText").textContent=`COIL PACK ${String(state.coilIndex).padStart(2,"0")}`;applyVisibility();focusSelection();log(`Coil pack ${state.coilIndex} isolated for inspection.`)}else if((s.includes("open")||s.includes("drill"))&&t){selectComponent(t);drill();log(`Opened ${active().name}.`)}else if(s.includes("isolate")&&t){selectComponent(t);state.isolate=true;applyVisibility();log(`Isolated ${active().name}.`)}else if(s.includes("xray")||s.includes("x-ray")){state.xray=!state.xray;applyVisibility();log(`X-ray ${state.xray?"enabled":"disabled"}.`)}else if(t){selectComponent(t);log(`Selected ${active().name}.`)}else log("Command not recognized.")}
$("run").onclick=command;$("cmd").onkeydown=e=>{if(e.key==="Enter")command()};
$("note").textContent=GEN.mark1.note;selectComponent("core");
try{init3D(THREE)}catch(err){console.error(err);$("fallback").style.display="grid";$("modelCode").textContent="3D MODULE OFFLINE"}