export const GEN={
 mark1:{title:"CAVE MINIATURE RT // MARK I",code:"RT-MK1-CAD",status:"SYSTEM NOMINAL",core:"Palladium",coils:"10 discrete packs",parts:"150+ meshes",tri:false,note:"Visual model prioritizes recognizable Mark I prop anatomy: ten copper wound coil packs, translucent outer light body, dark slotted aperture ring, three front spokes, concentric metallic collars and a mesh center. Palladium is canon; most detailed internal functions are not."},
 refined:{title:"REFINED PALLADIUM RT // GEN 02",code:"RT-PD-CAD",status:"PALLADIUM TOXICITY",core:"Palladium",coils:"10 precision packs",parts:"160+ meshes",tri:false,note:"The refined version keeps the same recognizable circular anatomy but presents cleaner machining, tighter windings and more precise housings. Palladium poisoning is canon; component-by-component engineering remains reconstructive."},
 mark6:{title:"NEW-ELEMENT RT // MARK VI",code:"RT-MK6-CAD",status:"NEW ELEMENT ACCEPTED",core:"New element",coils:"3 field sectors",parts:"120+ meshes",tri:true,note:"Mark VI is modeled as a genuinely different architecture: a triangular illuminated core frame, three primary supports/field sectors, segmented outer stator and circular containment body."}
};
export const C={
 core:{name:"Core Assembly",type:"canon",badge:"FILM-CONFIRMED CORE MATERIAL",definition:"The innermost assembly: active core cartridge or new-element module, concentric retainers, diffuser and front aperture.",makeup:"Early generations explicitly use palladium. Around it, this model separates the retaining collar, luminous diffuser, brass-toned contact ring and center mesh so each can be inspected independently.",role:"The central active region around which the rest of the RT's fictional power hardware is built.",canon:"Palladium is directly established for the early reactor, and Iron Man 2 establishes Tony's synthesized replacement element. The exact reaction physics are not published.",subs:[["core_cartridge","Palladium / element cartridge","CANON MATERIAL"],["core_collar","Core retaining collar","VISIBLE RECONSTRUCTION"],["brass_ring","Brass-toned contact ring","PROP-VISUAL"],["center_mesh","Center mesh face","PROP-VISUAL"],["core_diffuser","Luminous diffuser","PROP-VISUAL"]]},
 coils:{name:"Ten-Pack Coil Array",type:"visual",badge:"VISIBLE / PROP-BASED",definition:"Ten individually modeled electromagnetic-looking packs positioned around the reactor's outer illuminated body.",makeup:"Each pack is split into a dark rectangular core block, multiple closed copper wire loops, two side clamps and a terminal contact. The windings are real 3D loops, not a circular texture.",role:"The visible prop architecture strongly implies major electromagnetic hardware. This explorer treats the array as field-control / conditioning hardware without claiming Marvel specified that function.",canon:"The repeated wound packs are a highly recognizable visual feature. Exact wire gauge, core material, current, inductance and electrical purpose are not film-specified.",subs:[["coil_core","Coil core block","VISIBLE RECONSTRUCTION"],["coil_wire","Individual copper wire loops","PROP-VISUAL"],["coil_clamp","Side retaining clamps","PROP-VISUAL"],["coil_terminal","Coil terminal","ENGINEERING INFERENCE"]]},
 aperture:{name:"Slotted Aperture Assembly",type:"visual",badge:"VISIBLE / PROP-BASED",definition:"The dark inner annulus between the coil packs and the core, built from a structural ring, repeated slots/windows and three front retaining spokes.",makeup:"Dark annular plate, 28 bright window inserts, backing tabs, three metallic front spokes and concentric inner rings.",role:"Creates the highly recognizable mechanical face of the Mark I reactor and visually separates the outer coil system from the central core.",canon:"The geometry is grounded in the prop's visible design. Its exact fictional electrical or magnetic job is not stated.",subs:[["slot_ring","Dark slotted ring","PROP-VISUAL"],["slot_window","Aperture windows","PROP-VISUAL"],["front_spoke","Three front spokes","PROP-VISUAL"],["inner_ring","Concentric inner rings","PROP-VISUAL"]]},
 bus:{name:"Power Bus & Contacts",type:"infer",badge:"ENGINEERING INFERENCE",definition:"Internal radial links, terminals and conductor rings connecting the repeated hardware to the inner assembly.",makeup:"Copper-toned ring conductors, radial links and individual coil terminal contacts.",role:"Provides a readable power-routing model so the user can follow how repeated modules could connect electrically.",canon:"The reactor obviously must route power internally, but this exact topology is not an MCU-published wiring diagram.",subs:[["bus_ring","Circular bus conductor","INFERRED"],["bus_link","Radial power links","INFERRED"],["coil_terminal","Coil terminals","INFERRED"]]},
 housing:{name:"Containment & Housing",type:"visual",badge:"VISIBLE / PROP-BASED",definition:"Outer capture ring, translucent illuminated body, rear plate, perimeter clips and physical fasteners that hold the reactor together.",makeup:"Metallic front/rear rings, translucent acrylic-like light body, repeated perimeter blocks and screw heads.",role:"Provides structural alignment, mounting and physical protection for the inner layers.",canon:"The mechanical structure is clearly visible in the prop design. Exact alloy, tolerances and shielding performance are not established.",subs:[["outer_ring","Outer capture ring","PROP-VISUAL"],["light_body","Translucent light body","PROP-VISUAL"],["rear_plate","Rear housing plate","VISIBLE RECONSTRUCTION"],["fastener","Perimeter fasteners","PROP-VISUAL"],["mount_clip","Perimeter mount clips","PROP-VISUAL"]]},
 thermal:{name:"Rear Thermal Stage",type:"infer",badge:"ENGINEERING INFERENCE",definition:"A modeled rear heat-spreader layer and radial cooling fins that become obvious in side-section and exploded views.",makeup:"Rear metallic spreader disc plus repeated dark radial fins.",role:"Represents the type of thermal-management structure an extreme-density power source would plausibly require.",canon:"Marvel does not identify this exact layer as a thermal system. It is intentionally labeled engineering inference.",subs:[["heat_spreader","Rear heat spreader","INFERRED"],["heat_fin","Radial cooling fins","INFERRED"]]},
 interface:{name:"Load / Chest Interface",type:"canon",badge:"FILM-CONFIRMED SYSTEM FUNCTION",definition:"The modeled connector and contacts that represent the reactor's external electrical relationship to the chest electromagnet and armor systems.",makeup:"Connector body, paired contacts and short conductor links.",role:"Transfers reactor output to external loads. In the cave setup, the life-preserving electromagnet is a separate load powered by the RT.",canon:"The reactor-electromagnet relationship is explicit. The exact connector geometry and electrical standard are reconstruction.",subs:[["load_connector","External connector body","VISIBLE RECONSTRUCTION"],["load_contact","Power contacts","INFERRED"]]}
};