"use server";

/**
 * Portfolio report generation. Builds a plain-text/Markdown report from the LIVE
 * portfolio + risk model (same derivation as the pages), returned to the client
 * which downloads it as a file. No external service — the data never leaves.
 */
import { listHoldingsAction } from "@/server/actions/holdings";
import { buildPortfolio } from "@/data/portfolio-derive";
import { fetchHoldingQuotes } from "@/server/market/holding-quotes";
import { buildRiskAnalysis } from "@/data/risk-mock";

const usd = (n: number) =>
  `${n < 0 ? "-" : ""}$${Math.abs(n).toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
const pct = (n: number) => `${n >= 0 ? "+" : ""}${n.toFixed(2)}%`;

export async function generatePortfolioReportAction(): Promise<{ filename: string; content: string }> {
  const raw = await listHoldingsAction();
  const quotes = await fetchHoldingQuotes(raw.map((h) => h.symbol));
  const view = buildPortfolio(raw, quotes);
  const risk = buildRiskAnalysis(view);
  const s = view.summary;
  const m = risk.riskModel;

  const lines: string[] = [];
  lines.push("LEWIS WEALTH INTELLIGENCE — PORTFOLIO REPORT");
  lines.push("Lewis Family Holdings · Private Wealth");
  lines.push(`As of ${s.asOf}`);
  lines.push("=".repeat(60), "");

  lines.push("SUMMARY");
  lines.push("-".repeat(60));
  lines.push(`Total Value         ${usd(s.totalValue)}`);
  lines.push(`Total Gain / Loss   ${usd(s.totalGain)} (${pct(s.totalGainPct)})`);
  lines.push(`Day Change          ${usd(s.dayChangeUsd)} (${pct(s.dayChangePct)})`);
  lines.push(`Cost Basis          ${usd(s.totalCost)}`);
  lines.push(`Cash & Equivalents  ${usd(s.cash)}`);
  lines.push(`YTD Return          ${pct(s.ytdReturnPct)}`);
  lines.push(`Positions           ${s.holdingsCount}`);
  lines.push("");

  if (view.holdings.length > 0) {
    lines.push("HOLDINGS");
    lines.push("-".repeat(60));
    lines.push("Symbol   Qty        Price       Mkt Value     Weight   Gain");
    for (const h of [...view.holdings].sort((a, b) => b.marketValue - a.marketValue)) {
      lines.push(
        `${h.symbol.padEnd(8)} ${String(h.quantity).padStart(8)}  ${usd(h.price).padStart(10)}  ${usd(h.marketValue).padStart(12)}  ${`${h.weightPct.toFixed(1)}%`.padStart(6)}  ${pct(h.gainPct)}`,
      );
    }
    lines.push("");

    lines.push("ASSET ALLOCATION");
    lines.push("-".repeat(60));
    for (const a of view.assetAllocation) {
      lines.push(`${a.label.padEnd(20)} ${`${a.weightPct.toFixed(1)}%`.padStart(7)}   ${usd(a.value)}`);
    }
    lines.push("");

    lines.push("SECTOR ALLOCATION");
    lines.push("-".repeat(60));
    for (const a of view.sectorAllocation) {
      lines.push(`${a.label.padEnd(24)} ${`${a.weightPct.toFixed(1)}%`.padStart(7)}`);
    }
    lines.push("");

    lines.push("RISK ANALYSIS");
    lines.push("-".repeat(60));
    lines.push(`Composite Risk Score   ${m.riskScore} (${m.riskTier})`);
    lines.push(`Portfolio Beta         ${m.portfolioBeta.toFixed(2)}`);
    lines.push(`Volatility (annual)    ${m.portfolioVol.toFixed(1)}%`);
    lines.push(`Sharpe Ratio           ${m.sharpe.toFixed(2)}`);
    lines.push(`Max Drawdown           ${pct(m.maxDrawdownPct)}`);
    lines.push(`1-Day VaR (95%)        ${usd(m.var95Usd)}`);
    lines.push(`Top Holding            ${risk.concentration.top1Pct.toFixed(1)}%`);
    lines.push(`Top-5 Concentration    ${risk.concentration.top5Pct.toFixed(1)}%`);
    lines.push(`Largest Sector         ${risk.concentration.topSectorLabel} (${risk.concentration.topSectorPct.toFixed(1)}%)`);
    lines.push("");
  } else {
    lines.push("No holdings — add positions on the Portfolio tab to populate this report.");
    lines.push("");
  }

  lines.push("=".repeat(60));
  lines.push(
    "DISCLAIMER: Generated by Lewis Wealth Intelligence for informational purposes only.",
    "Figures are illustrative and not personalized investment advice or a recommendation",
    "to buy or sell any security. Review with a qualified advisor before acting.",
  );

  const stamp = new Date().toISOString().slice(0, 10);
  return { filename: `Lewis-Wealth-Portfolio-Report-${stamp}.txt`, content: lines.join("\n") };
}
